### ISSUE TITLE
Workflow Meter BG doesn't´t Work

### ISSUE THREAD

**Issue by Byketol** [ella7/nightscout-workflows#1]
Hi i have installed the Workflow app on my Iphone 7. So if i start the workflow and enter the BG after that there is a push with that.
Something went wrong and it appears the entry was not saved in Nightscout.
How can i check what went wrong?

**Comment by christerjensen** [comment]
Same here. Tried adding HTTPS etc infront of the specified URL syntax without luck.

**Comment by ryanpacker** [comment]
Thanks for trying this out. What do you have for the NS URL? Did you include "/api/v1/treatments.json" at the end?

**Comment by ryanpacker** [comment]
Thinking about this more, two things come to mind:

1. The first thing to check is that the URL is correct. 

- Open the Meter BG workflow
- Scroll down to the URL section (see screenshot)
![ns-workflow-debug](https://user-images.githubusercontent.com/3837984/35075344-c50aff6e-fbaf-11e7-8763-bf67e568dab2.jpg)
- Select all of the URL and then copy
- Open Safari and then paste and tap "Go"
- You should get a large JSON response - a lot of text that will start with something like `[{"_id":"5a5fe416e07abb4f8b1b47ff"...`
- If you do not get a JSON response, either your URL is not correct, or something isn't properly configured within Nightscout. I'd love to know so I can make instructions and the workflows easier.

2. The second thing to check is the hashed API secret. 

- I need to provide documentation for what this is. 
- For now, please refer to [the Open APS docs on this topic](http://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/ifttt-integration.html#ifttt-setup-for-phones
).
- I suspect this might be the problem. Obviously have work to do to make this super easy for anyone who wants to use it, so thanks for your patience and feedback as I work to make the needed changes.

**Comment by Byketol** [comment]
My Nightscout URL is https://diabetes-engel.herokuapp.com/api/v1/treatments.json
So i think the url is ok.
I think is the key.
I thought the Nightscout site’s API is the same like the number for the Workflow.

**Comment by Byketol** [comment]
So with the right number (your link on 2) is every thing god.
Thank you.

**Comment by ryanpacker** [comment]
I'm glad that worked. In the version I'm checking into the dev branch now, I've made both things easier. It will no longer be required to enter the full endpoint URL, and you will be able to enter your normal API secret, not the hashed secret. Thanks so much for the feedback.

**Comment by ryanpacker** [comment]
I suspect the issue here is the hashed API. Documentation has been updated and the new version will resolve permanently. Marking this as resolved.
